export const ACHIEVEMENT_DEFINITIONS = [
  {
    key: 'first_task',
    title: '起步',
    description: '完成第一个任务',
    icon: '🌱',
    category: 'consistency' as const,
    levels: [
      { level: 1, target: 1, title: '起步' },
      { level: 2, target: 10, title: '小成' },
      { level: 3, target: 50, title: '精进' },
      { level: 4, target: 200, title: '达人' },
      { level: 5, target: 500, title: '大师' },
    ],
  },
  {
    key: 'streak',
    title: '连续达人',
    description: '连续多天完成任务',
    icon: '🔥',
    category: 'consistency' as const,
    levels: [
      { level: 1, target: 3, title: '三日连' },
      { level: 2, target: 7, title: '一周坚持' },
      { level: 3, target: 21, title: '习惯养成' },
      { level: 4, target: 66, title: '百日筑基' },
      { level: 5, target: 365, title: '年度坚持' },
    ],
  },
  {
    key: 'focus_hours',
    title: '专注达人',
    description: '累计专注时长',
    icon: '⏱️',
    category: 'efficiency' as const,
    levels: [
      { level: 1, target: 60, title: '初学乍练' },
      { level: 2, target: 300, title: '小有所成' },
      { level: 3, target: 1000, title: '专注能手' },
      { level: 4, target: 3000, title: '心流大师' },
      { level: 5, target: 10000, title: '一万小时' },
    ],
  },
  {
    key: 'goal_completed',
    title: '目标猎手',
    description: '完成的目标型任务',
    icon: '🎯',
    category: 'growth' as const,
    levels: [
      { level: 1, target: 5, title: '瞄准' },
      { level: 2, target: 20, title: '命中' },
      { level: 3, target: 50, title: '神射手' },
      { level: 4, target: 100, title: '百步穿杨' },
      { level: 5, target: 300, title: '传奇猎手' },
    ],
  },
  {
    key: 'early_bird',
    title: '早起鸟',
    description: '上午8点前完成任务',
    icon: '🌅',
    category: 'efficiency' as const,
    levels: [
      { level: 1, target: 5, title: '初试啼声' },
      { level: 2, target: 20, title: '晨型人' },
      { level: 3, target: 50, title: '破晓者' },
      { level: 4, target: 100, title: '晨光使者' },
      { level: 5, target: 365, title: '日出之神' },
    ],
  },
  {
    key: 'night_owl',
    title: '夜猫子',
    description: '晚上10点后完成任务',
    icon: '🦉',
    category: 'efficiency' as const,
    levels: [
      { level: 1, target: 5, title: '夜猫入门' },
      { level: 2, target: 20, title: '夜行侠' },
      { level: 3, target: 50, title: '午夜行者' },
      { level: 4, target: 100, title: '暗夜精灵' },
      { level: 5, target: 365, title: '星月之主' },
    ],
  },
  {
    key: 'review_streak',
    title: '复盘达人',
    description: '连续写复盘',
    icon: '📝',
    category: 'growth' as const,
    levels: [
      { level: 1, target: 3, title: '开始反思' },
      { level: 2, target: 7, title: '周周复盘' },
      { level: 3, target: 30, title: '月月精进' },
      { level: 4, target: 100, title: '复盘大师' },
      { level: 5, target: 365, title: '日新又新' },
    ],
  },
  {
    key: 'team_player',
    title: '团队协作者',
    description: '参与团队任务',
    icon: '🤝',
    category: 'collaboration' as const,
    levels: [
      { level: 1, target: 3, title: '初识团队' },
      { level: 2, target: 10, title: '团队成员' },
      { level: 3, target: 30, title: '核心力量' },
      { level: 4, target: 100, title: '协作达人' },
      { level: 5, target: 300, title: '团队之光' },
    ],
  },
  {
    key: 'blocker_breaker',
    title: '卡点突破者',
    description: '突破卡点任务',
    icon: '💪',
    category: 'growth' as const,
    levels: [
      { level: 1, target: 1, title: '初次突破' },
      { level: 2, target: 5, title: '迎难而上' },
      { level: 3, target: 20, title: '破局者' },
      { level: 4, target: 50, title: '卡点克星' },
      { level: 5, target: 100, title: '无坚不摧' },
    ],
  },
  {
    key: 'template_creator',
    title: '方法论专家',
    description: '创建任务模板',
    icon: '📋',
    category: 'growth' as const,
    levels: [
      { level: 1, target: 1, title: '模板初成' },
      { level: 2, target: 5, title: '方法沉淀' },
      { level: 3, target: 15, title: '体系构建' },
      { level: 4, target: 30, title: '方法论者' },
      { level: 5, target: 50, title: '知识管理大师' },
    ],
  },
];

export const CATEGORY_LABELS: Record<string, { label: string; color: string }> = {
  efficiency: { label: '效率', color: 'text-emerald-600 bg-emerald-50 dark:text-emerald-400 dark:bg-emerald-950/30' },
  consistency: { label: '坚持', color: 'text-orange-600 bg-orange-50 dark:text-orange-400 dark:bg-orange-950/30' },
  growth: { label: '成长', color: 'text-indigo-600 bg-indigo-50 dark:text-indigo-400 dark:bg-indigo-950/30' },
  collaboration: { label: '协作', color: 'text-rose-600 bg-rose-50 dark:text-rose-400 dark:bg-rose-950/30' },
};
